# values.yaml
replicaCount:
  keycloak: 2
  apache2: 2

image:
  keycloak:
    repository: quay.io/keycloak/keycloak
    tag: 26.1.1
    pullPolicy: IfNotPresent
  apache2:
    repository: elhee/apache
    tag: 0.2
    pullPolicy: Always
  postgres:
    repository: postgres
    tag: 15
    pullPolicy: IfNotPresent

service:
  keycloak:
    type: ClusterIP
    port: 8080
#    http: 8080    # Keycloak 컨테이너 포트
  apache2:
    type: ClusterIP
    port: 4433


ingress:
  enabled: true
  ingressClassName: nginx
  tls:
    secretName: keycloak-tls     # ← 템플릿에서 .ingress.tls.secretName
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
  host: key.elhee.site
  host2: euc.elhee.site

egress:
  enabled: true
  dbIp: "192.168.0.190/32"  # 외부 PostgreSQL DB IP
  dbPort: 5432         # 외부 DB 포트


persistence:
  storageClass: local-path     # 사용할 StorageClass 이름
  #hostPath: ./volume/postgresql/data
  #mountPath: /var/lib/postgresql/data
  size:
#    postgres: 10Gi          # Postgres 데이터 저장용 PVC 크기
    keycloak: 1Gi           # (옵션) 키클락 영속 저장소 크기
    apache2: 1Gi
