apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard        # 원하는 이름으로 변경 가능
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
