apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: apache-app
  name: apache-app
spec:
  ports:
  - name: "4433"
    port: 4433
    targetPort: 80
  selector:
    io.kompose.service: apache-app
status:
  loadBalancer: {}
