apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/session-cookie-path: "/"
    nginx.ingress.kubernetes.io/session-cookie-secure: "true"
    nginx.ingress.kubernetes.io/session-cookie-samesite: "None"
    nginx.ingress.kubernetes.io/session-cookie-name: "INGRESS_KC"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/affinity: "cookie"


spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    - {{ .Values.ingress.host2 }}
    secretName: {{ .Values.ingress.tls.secretName }}
  rules:
    - host: key.elhee.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 80
    - host: euc.elhee.site
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: nodejs
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apache2
                port:
                  number: 80