#service
apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  type: {{ .Values.service.nodejs.type }}
  ports:
  - port: {{ .Values.service.nodejs.port }}
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: nodejs
