
{{- if .Values.egress.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-egress
  namespace: keycloak
spec:
  podSelector:
    matchLabels:
      app: keycloak
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: {{ .Values.egress.dbIp }}
      ports:
        - protocol: TCP
          port: {{ .Values.egress.dbPort }}
{{- end }}