# templates/keycloak-deployment.yaml
apiVersion: apps/v1
#kind: Deployment
kind: StatefulSet
metadata:
  name: keycloak
spec:
  serviceName: keycloak-discovery  # headless service 이름
  replicas: {{ .Values.replicaCount.keycloak }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      affinity:                # 노드별 1개 보장(Optional)
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels: { app: keycloak }
                topologyKey: kubernetes.io/hostname
      containers:                     
      - name: keycloak
        image: "{{ .Values.image.keycloak.repository }}:{{ .Values.image.keycloak.tag }}"
        imagePullPolicy: {{ .Values.image.keycloak.pullPolicy }}
        #args: ["start", "--http-enabled=true" ,"--hostname=key.elhee.site" ,"--hostname-strict=false"]


        args:
          - start
#         - --http-enabled=true 
#         - --hostname=https://key.elhee.site
#         - --hostname-strict=true 
#         - --hostname-backchannel-dynamic=true 
          - --http-port=9999
#         - --cache=ispn
#         - --cache-stack=kubernetes
#          - -Djgroups.dns.query=keycloak-cluster.keycloak.svc.cluster.local


        ports:
        - name: http
          containerPort: {{ .Values.service.keycloak.port }}
        env:
        - name: KC_DB
          value: postgres
        - name: KC_DB_PASSWORD
          value: password
        - name: KC_DB_URL
          value: jdbc:postgresql://192.168.0.190:5432/keycloak
        - name: KC_DB_USERNAME
          value: keycloak
        - name: KC_HTTP_ENABLED
          value: "true"                     
        - name: KC_HOSTNAME
          value: "https://key.elhee.site"       
        - name: KC_HOSTNAME_STRICT
          value: "true"
        - name: KC_HOSTNAME_BACKCHANNEL_DYNAMIC
          value: "true"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "true"
#        - name: KC_PROXY
#          value: "edge"
        - name: KC_PROXY_HEADERS
          value: "xforwarded"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KEYCLOAK_ADMIN
          value: "admin" 
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin" 
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_CACHE
          value: "ispn"
        - name: 'KC_CACHE_STACK'
          value: 'kubernetes'
        - name: JAVA_OPTS_APPEND
         value: "-Djgroups.dns.query=keycloak-discovery.keycloak.svc.cluster.local"

        volumeMounts:
          - name: theme-volume
            mountPath: /opt/keycloak/providers
      volumes:
      - name: theme-volume
        hostPath:
          path: /home/ubuntu/keycloak-themes
          type: Directory


#  volumeClaimTemplates:
#  - metadata:
#      name: keycloak-storage
#    spec:
#      accessModes: ["ReadWriteOnce"]
#      storageClassName: {{ .Values.persistence.storageClass }}
#      resources:
#        requests:
#          storage: {{ .Values.persistence.size.keycloak }}