# templates/keycloak-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: {{ .Values.service.keycloak.type }}
  ports:
  - port: {{ .Values.service.keycloak.port }}
    targetPort: {{ .Values.service.keycloak.port }}
    protocol: TCP
    name: http
  selector:
    app: keycloak